version: '3.7'

services:

  server:
    container_name: server
    depends_on:
      - db
    build:
      context: server
      dockerfile: Dockerfile.ubuntu
    working_dir: /var/app/current
    ports:
      - "8082:8082"
      - "9227:9229"
    stdin_open: true
    tty: true
    volumes:
      - "./server:/var/app/current"
    command: sh -c "bash /var/app/current/docker_init.sh"

  reactjs:
    container_name: reactjs
    tty: true
    depends_on:
      - server
    build:
      context: reactjs
      dockerfile: Dockerfile
    working_dir: /client
    ports:
      - "3000:3000"
    volumes:
      - "./reactjs:/client"
    command: sh -c "bash /client/docker_init.sh"

  db:
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    container_name: db
    restart: "no"
    build:
      context: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      #MYSQL_DATABASE: users
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/mysqldocker:/var/lib/mysql
      - ./mysql:/mysql
